import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';

import { Providers } from '@/layouts/Providers';

const CustomApp = ({ Component, pageProps }: AppProps) => {
  return (
    <Providers>
      <Head>
        <title>Free Next.js Template for Startup and SaaS</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </Providers>
  );
};

export default CustomApp;
