---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: auth
          image: zineof/f-tickets
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: DATABASE_URL
              value: 'postgresql://postgres:postgres@tickets-pg-srv/db?schema=public'
            - name: COOKIE_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: domain
                  key: DOMAIN
            - name: KAFKA_BROKERS
              value: 'kafka-service:9092'
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
